### ISSUE TITLE
Last features before launch

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/pdr-web#104]
- [ ] Update to support new contracts
- [ ] Stabilize and improve performance of current app
- [ ] Improve buy subscription flow(give more feedback on the steps and an overview of what does steps are)
- [ ] Display statistics(prediction accuracy % on last 24h for each asset, overall accuracy of predictions)
- [ ] Make it more obvious for the user when to set the trade
- [ ] Give more info on the history prediction(how it ended, was it accurate)
- [ ] Make direction and confidence values more easier for user to understand
- [ ] Write an how to use app docs page
