### ISSUE TITLE
[EPIC] Frontend support for 60min feeds

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/pdr-web#161]
### About

Motivation + backend issue: [pdr-backend#144](https://github.com/oceanprotocol/pdr-backend/issues/144)

We need to support this in frontend too.

### Towards a solution

One challenge: in the app, the table's header has labels that are specific for 5 min feeds. E.g. "13:55, 14:00, 14:05". This was done on purpose to help simplify the mental model.
- We already discussed a solution: have a _separate table_ for each time scale. Since we won't ever have that many timescales (e.g. 5 min, 60 min, 24h). 
- One possible implementation: Have all tables "tabbed". Each tab is right above the table header. There's a tab labeled "5m", another "60m", etc. 

### Requirements
- Pre-requisite: pdr-backend supports 60-min feeds locally & on remote testnet (most of their work on pdr-backend 144)
- Design: Implementation discussed and signed off. Tab-like solution to be implemented.

### DoD:
- [x] Create 5m and 60m timeframe tabs 
- [x] User is able to click between tabs to see all feeds
- [x] App refetches data and presents it to the user as required
