### ISSUE TITLE
Predictoor Mainnet - Oct 10

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-web#213]
### Key Features
- Users can access/buy feeds deployed in mainnet
- 60 minute feeds available in FE

### DoD
- [x] App gets and filters feeds based on timeframes [pdr-web 205](https://app.zenhub.com/workspaces/s3-predictoor-642ce98aa2ed9d00173ef51f/issues/gh/oceanprotocol/pdr-web/205), [pdr-websockets 40](https://github.com/oceanprotocol/pdr-websocket/issues/40)
- [x] User is able to tab between 5min and 60min feed timeframes. Epochs, Table headers, and many other things update naturally. [pdr-web 205](https://app.zenhub.com/workspaces/s3-predictoor-642ce98aa2ed9d00173ef51f/issues/gh/oceanprotocol/pdr-web/205)
- [x] User is able to purchase different subscriptions from different timeframes. [pdr-web 205](https://app.zenhub.com/workspaces/s3-predictoor-642ce98aa2ed9d00173ef51f/issues/gh/oceanprotocol/pdr-web/205)
- [x] Subscription UI is updated, column can be removed, and more of this friction moves to the background [pdr-web 176](https://app.zenhub.com/workspaces/s3-predictoor-642ce98aa2ed9d00173ef51f/issues/gh/oceanprotocol/pdr-web/176)
- [x] Add Terms and Conditions for using app and make it accessible. [pdr-private 42](https://app.zenhub.com/workspaces/s3-predictoor-642ce98aa2ed9d00173ef51f/issues/gh/oceanprotocol/pdr-private/42)
- [x] Display total tokens staked over last 24h as a new column inside the app [pdr-web 205](https://app.zenhub.com/workspaces/s3-predictoor-642ce98aa2ed9d00173ef51f/issues/gh/oceanprotocol/pdr-web/206)
- [x] Add free 1h BTC/USDT feed [pdr-websockets 42](https://github.com/oceanprotocol/pdr-websocket/issues/42)
- [x] pdr FE stack deployed on prod VM, points to Oasis mainnet
- [x] pdr-websockets deployed on prod VM, points to Oasis mainnet
- [x] pdr-web deployed on prod VM, points to Oasis mainnet

**Comment by graceful-coder** [comment]
Marketing tasks for Predictoor Mainnet announcement:

- [ ] Get the visual from Lorente
- [ ] Schedule X.com post
- [ ] Share the X copy with Ocean collaborators
- [ ] Send Telegram copy to Guerrilla Marketing for posting at the same time as X.com
- [ ] Request OPAP team to create buzz shortly after the announcement and organize the next bounty RT contest about the announcement
- [ ] After the X.com post goes live, then ask Casiana to post on LinkedIn immediately (until I get access to LinkedIn). Send her the LinkedIn announcement copy link: https://docs.google.com/document/d/19qe7f39yICl9lZpBDM3r0yh7FyxZAXDbof4AFtgSV-Q/edit 
- [ ] Pass blogpost copy to Trent, then post at the same time as X.com post
- [ ] Post the announcement on the #Predictoor channel in Ocean Discord
