### ISSUE TITLE
1-click TG trader bot OR integrate with existing bots OR both

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-web#81]
### Overall

_Many_ TG-based trading bots have emerged. Some with Ms of users. 

We have options:
1. build our own bot
2. integrate to other bots --> see [pdr-private#50](https://github.com/oceanprotocol/pdr-private/issues/50)
3. both (1) and (2). Doing (1) can give us insight for (2).

### Details of (1): One-click trader bot
Pitch for feature is laid out in figma.
Unibot is one of the fastest growing trading apps... users are literally giving the PKs to it.

Solution:
- [ ] Traders can deploy a bot that is secure and does not risk their private information. Your bot, your keys.
- [ ] "Make it easy" for traders trade, see the results in-app, in less than 3 minutes.
- [ ] Users just need to: get cloud account + configure bot + 1-click deploy.
- [ ] Cloud client + UI client should automatically connect, read logs from bot, & show trading results in UI
